Repository EVerest/everest-core, pull requests merged in 2024-02, with the labels that each got.

#437 Add tests that simply run all (SIL) configs in everest-core/config
  tests/README.md
  tests/conftest.py
  tests/core_tests/config_tests.py
  tests/pytest.ini
Labels: CI/CD, testing

#537 Fix DC full power on reason and shutdown in PreCharge
  modules/EvseManager/Charger.cpp
Labels: bug

#540 Bugfix/transition to preparecharging after waitingforenergy
  modules/EvseManager/Charger.cpp
Labels: bug

#528 Adapt unit tests
  CMakeLists.txt
Labels: testing
