Repository EVerest/everest-core, pull requests merged in 2024-03, with the labels that each got.

#530 Feature/random delays
  config/config-sil-energy-management.yaml
  interfaces/uk_random_delay.yaml
  modules/API/API.cpp
  modules/API/API.hpp
  modules/API/README.md
  modules/API/manifest.yaml
  modules/EnergyManager/EnergyManager.cpp
  modules/EnergyManager/EnergyManager.hpp
  modules/EnergyManager/Market.cpp
  modules/EvseManager/CMakeLists.txt
  modules/EvseManager/Charger.cpp
  modules/EvseManager/EvseManager.cpp
  modules/EvseManager/EvseManager.hpp
  modules/EvseManager/energy_grid/energyImpl.cpp
  modules/EvseManager/energy_grid/energyImpl.hpp
  modules/EvseManager/manifest.yaml
  modules/EvseManager/random_delay/uk_random_delayImpl.cpp
  modules/EvseManager/random_delay/uk_random_delayImpl.hpp
  types/energy.yaml
  types/uk_random_delay.yaml
Labels: enhancement

#447 Feature/add error history module
  dependencies.yaml
  interfaces/error_history.yaml
  module-dependencies.cmake
  modules/CMakeLists.txt
  modules/ErrorHistory/CMakeLists.txt
  modules/ErrorHistory/ErrorDatabaseSqlite.cpp
  modules/ErrorHistory/ErrorDatabaseSqlite.hpp
  modules/ErrorHistory/ErrorHistory.cpp
  modules/ErrorHistory/ErrorHistory.hpp
  modules/ErrorHistory/error_history/error_historyImpl.cpp
  modules/ErrorHistory/error_history/error_historyImpl.hpp
  modules/ErrorHistory/manifest.yaml
  modules/ErrorHistory/tests/CMakeLists.txt
  modules/ErrorHistory/tests/error_database_sqlite_tests.cpp
  modules/ErrorHistory/tests/helpers.cpp
  modules/ErrorHistory/tests/helpers.hpp
  tests/conftest.py
  tests/core_tests/error_history_tests.py
  tests/everest-core_tests/config/config-test-error-history-module.yaml
  tests/everest-core_tests/modules/TestErrorHandling/main/test_error_handlingImpl.cpp
  types/error_history.yaml
Labels: post-release

#601 libgpio: fix description
  lib/staging/gpio/gpio.hpp
Labels: include-in-release

#608 fix: parameter needs to be pass by reference rather than value
  modules/EvseManager/ErrorHandling.cpp
  modules/EvseManager/ErrorHandling.hpp
  modules/EvseManager/tests/ErrorHandlingTest.cpp
Labels: include-in-release
