Repository EVerest/everest-core, pull requests merged in 2025-02, with the labels that each got.

#1037 Updating libcbv2g to latest version (v0.3.0)
  dependencies.yaml
Labels: include-in-release

#1030 Integrates the security module in the Evse15118D20 module
  config/config-sil-dc-d20.yaml
  config/config-sil-dc-isomux-tls.yaml
  config/config-sil-dc-isomux.yaml
  dependencies.yaml
  modules/Evse15118D20/Evse15118D20.hpp
  modules/Evse15118D20/charger/ISO15118_chargerImpl.cpp
  modules/Evse15118D20/manifest.yaml
Labels: include-in-release

#1031 Bump everest-framework and ev-cli for clear_error refactor
  cmake/ev-project-bootstrap.cmake
  dependencies.yaml
  modules/Cargo.lock
  modules/Cargo.toml
Labels: include-in-release

#1042 Bump everest-framework to v0.20.1
  dependencies.yaml
  modules/Cargo.lock
  modules/Cargo.toml
Labels: include-in-release

#1046 Bump libevse security dependency to 0.9.3
  dependencies.yaml
Labels: include-in-release

#1045 Bump everest-framework dependency to 0.20.2
  dependencies.yaml
  modules/Cargo.lock
  modules/Cargo.toml
Labels: include-in-release

#1052 cmake: install missed cmake file
  cmake/everest-generate.cmake
Labels: include-in-release

#1022 Adding new iso15118_extension interface
  config/config-sil-dc-isomux-tls.yaml
  config/config-sil-dc-isomux.yaml
  config/config-sil-ocpp-pnc.yaml
  config/config-sil-ocpp201-pnc.yaml
  interfaces/ISO15118_charger.yaml
  interfaces/evse_manager.yaml
  interfaces/iso15118_extensions.yaml
  modules/DummyV2G/main/ISO15118_chargerImpl.cpp
  modules/DummyV2G/main/ISO15118_chargerImpl.hpp
  modules/Evse15118D20/CMakeLists.txt
  modules/Evse15118D20/Evse15118D20.cpp
  modules/Evse15118D20/Evse15118D20.hpp
  modules/Evse15118D20/charger/ISO15118_chargerImpl.cpp
  modules/Evse15118D20/charger/ISO15118_chargerImpl.hpp
  modules/Evse15118D20/extensions/iso15118_extensionsImpl.cpp
  modules/Evse15118D20/extensions/iso15118_extensionsImpl.hpp
  modules/Evse15118D20/manifest.yaml
  modules/EvseManager/EvseManager.cpp
  modules/EvseManager/evse/evse_managerImpl.cpp
  modules/EvseManager/evse/evse_managerImpl.hpp
  modules/EvseManager/tests/EvseManagerStub.hpp
  modules/EvseV2G/CMakeLists.txt
  modules/EvseV2G/EvseV2G.cpp
  modules/EvseV2G/EvseV2G.hpp
  modules/EvseV2G/charger/ISO15118_chargerImpl.cpp
  modules/EvseV2G/charger/ISO15118_chargerImpl.hpp
  modules/EvseV2G/extensions/iso15118_extensionsImpl.cpp
  modules/EvseV2G/extensions/iso15118_extensionsImpl.hpp
  modules/EvseV2G/iso_server.cpp
  modules/EvseV2G/manifest.yaml
  modules/EvseV2G/tests/ISO15118_chargerImplStub.hpp
  modules/EvseV2G/tests/iso15118_extensionsImplStub.hpp
  modules/EvseV2G/tests/v2g_ctx_test.cpp
  modules/EvseV2G/tests/v2g_main.cpp
  modules/EvseV2G/v2g.hpp
  modules/EvseV2G/v2g_ctx.cpp
  modules/EvseV2G/v2g_ctx.hpp
  modules/IsoMux/CMakeLists.txt
  modules/IsoMux/IsoMux.cpp
  modules/IsoMux/IsoMux.hpp
  modules/IsoMux/charger/ISO15118_chargerImpl.cpp
  modules/IsoMux/charger/ISO15118_chargerImpl.hpp
  modules/IsoMux/extensions/iso15118_extensionsImpl.cpp
  modules/IsoMux/extensions/iso15118_extensionsImpl.hpp
  modules/IsoMux/manifest.yaml
  modules/OCPP/OCPP.cpp
  modules/OCPP/OCPP.hpp
  modules/OCPP/doc.rst
  modules/OCPP/manifest.yaml
  modules/OCPP201/OCPP201.cpp
  modules/OCPP201/OCPP201.hpp
  modules/OCPP201/doc.rst
  modules/OCPP201/manifest.yaml
  tests/ocpp_tests/conftest.py
  tests/ocpp_tests/test_sets/everest-aux/config/everest-config-ocpp201-probe-module-data-transfer.yaml
  tests/ocpp_tests/test_sets/everest-aux/config/everest-config-ocpp201-probe-module.yaml
  tests/ocpp_tests/test_sets/everest-aux/config/everest-config-sil-iso.yaml
  tests/ocpp_tests/test_sets/ocpp16/ocpp_generic_interface_integration_tests.py
  tests/ocpp_tests/test_sets/ocpp201/iso15118_certificate_management.py
Labels: post-release

#1054 Fixing DcPowerSupplySimulator race condition
  modules/simulation/DCSupplySimulator/main/power_supply_DCImpl.hpp
Labels: post-release

#1050 Refactoring iso15118 EVerest types
  interfaces/ISO15118_charger.yaml
  interfaces/ISO15118_ev.yaml
  interfaces/iso15118_extensions.yaml
  modules/DummyV2G/main/ISO15118_chargerImpl.cpp
  modules/DummyV2G/main/ISO15118_chargerImpl.hpp
  modules/EvManager/main/car_simulation.cpp
  modules/Evse15118D20/charger/ISO15118_chargerImpl.cpp
  modules/Evse15118D20/charger/ISO15118_chargerImpl.hpp
  modules/Evse15118D20/charger/utils.hpp
  modules/Evse15118D20/extensions/iso15118_extensionsImpl.cpp
  modules/Evse15118D20/extensions/iso15118_extensionsImpl.hpp
  modules/EvseManager/Charger.cpp
  modules/EvseManager/Charger.hpp
  modules/EvseManager/ErrorHandling.cpp
  modules/EvseManager/EvseManager.cpp
  modules/EvseManager/EvseManager.hpp
  modules/EvseManager/energy_grid/energyImpl.cpp
  modules/EvseManager/evse/evse_managerImpl.cpp
  modules/EvseV2G/charger/ISO15118_chargerImpl.cpp
  modules/EvseV2G/charger/ISO15118_chargerImpl.hpp
  modules/EvseV2G/din_server.cpp
  modules/EvseV2G/extensions/iso15118_extensionsImpl.cpp
  modules/EvseV2G/extensions/iso15118_extensionsImpl.hpp
  modules/EvseV2G/iso_server.cpp
  modules/EvseV2G/tests/ISO15118_chargerImplStub.hpp
  modules/EvseV2G/tests/iso15118_extensionsImplStub.hpp
  modules/EvseV2G/tools.cpp
  modules/EvseV2G/tools.hpp
  modules/EvseV2G/v2g_ctx.cpp
  modules/EvseV2G/v2g_server.cpp
  modules/IsoMux/charger/ISO15118_chargerImpl.cpp
  modules/IsoMux/charger/ISO15118_chargerImpl.hpp
  modules/IsoMux/extensions/iso15118_extensionsImpl.cpp
  modules/IsoMux/extensions/iso15118_extensionsImpl.hpp
  modules/IsoMux/tools.cpp
  modules/IsoMux/tools.hpp
  modules/OCPP/OCPP.cpp
  modules/OCPP/conversions.cpp
  modules/OCPP/conversions.hpp
  modules/OCPP201/OCPP201.cpp
  modules/OCPP201/conversions.cpp
  modules/OCPP201/conversions.hpp
  modules/PyEvJosev/module.py
  modules/simulation/JsEvManager/index.js
  types/authorization.yaml
  types/iso15118.yaml
  types/iso15118_charger.yaml
  types/iso15118_ev.yaml
Labels: post-release

#1021 feat: add TPM2 support for EvseV2G TLS server private key
  lib/staging/tls/openssl_util.cpp
  lib/staging/tls/tests/CMakeLists.txt
  lib/staging/tls/tests/gtest_main.cpp
  lib/staging/tls/tests/openssl_util_test.cpp
  lib/staging/tls/tests/pki/pki-tpm.sh
  lib/staging/tls/tests/tls_connection_test.cpp
  lib/staging/tls/tests/tls_connection_test.hpp
  lib/staging/tls/tests/tls_connection_test_tpm.cpp
  lib/staging/tls/tests/tls_main.cpp
  lib/staging/tls/tls.cpp
Labels: post-release

#1064 Fix missing enum conversion for CertificateValidationResult::Expired
  lib/staging/evse_security/CMakeLists.txt
  lib/staging/evse_security/conversions.cpp
Labels: bug

#905 Fix debug output of EV max voltage
  modules/EvseManager/EvseManager.cpp
Labels: include-in-release

#1065 remove everest-modbus dependency
  CMakeLists.txt
Labels: include-in-release

#1067 Reservation Handling in EvseManager
  dependencies.yaml
  modules/Auth/lib/AuthHandler.cpp
  modules/Auth/tests/reservation_tests.cpp
  modules/EvseManager/EvseManager.cpp
  modules/EvseManager/evse/evse_managerImpl.cpp
Labels: include-in-release
