Repository EVerest/everest-core, pull requests merged in 2025-04, with the labels that each got.

#1012 Remove unused functions from evsev2g
  modules/EvseV2G/charger/ISO15118_chargerImpl.cpp
  modules/EvseV2G/connection/connection.cpp
  modules/EvseV2G/din_server.cpp
  modules/EvseV2G/iso_server.cpp
  modules/EvseV2G/tests/din_server_test.cpp
  modules/EvseV2G/tests/v2g_ctx_test.cpp
  modules/EvseV2G/tools.cpp
  modules/EvseV2G/tools.hpp
  modules/EvseV2G/v2g.hpp
  modules/EvseV2G/v2g_ctx.cpp
  modules/EvseV2G/v2g_ctx.hpp
Labels: post-release

#1131 Auth module: Unlock before token validation callbacks
  modules/Auth/lib/AuthHandler.cpp
  modules/Auth/tests/auth_tests.cpp
Labels: bug

#1143 Update libcurl to 8.13.0
  dependencies.yaml
  module-dependencies.cmake
Labels: include-in-release

#1140 RsPaymentTerminal: Update zvt dependency
  modules/Cargo.lock
  modules/RsPaymentTerminal/Cargo.toml
Labels: include-in-release

#1144 Fix: Sending correct ResponseCode if the pnc contract certs are revoked
  modules/EvseV2G/iso_server.cpp
  tests/ocpp_tests/test_sets/ocpp201/plug_and_charge_tests201.py
Labels: include-in-release

#1141 Reduce warnings in OCPP integration tests
  tests/ocpp_tests/conftest.py
  tests/ocpp_tests/pytest.ini
  tests/ocpp_tests/requirements.txt
  tests/ocpp_tests/test_sets/everest_test_utils.py
  tests/ocpp_tests/test_sets/ocpp16/authorization_tests.py
  tests/ocpp_tests/test_sets/ocpp16/booting.py
  tests/ocpp_tests/test_sets/ocpp16/broken.py
  tests/ocpp_tests/test_sets/ocpp16/california_pricing_ocpp16.py
  tests/ocpp_tests/test_sets/ocpp16/firmware_and_diagnostics_tests.py
  tests/ocpp_tests/test_sets/ocpp16/message_queue.py
  tests/ocpp_tests/test_sets/ocpp16/ocpp_compliance_tests.py
  tests/ocpp_tests/test_sets/ocpp16/smart_charging_profiles/absolute_profiles.py
  tests/ocpp_tests/test_sets/ocpp16/smart_charging_profiles/combined_profiles.py
  tests/ocpp_tests/test_sets/ocpp16/smart_charging_profiles/recurring_profiles.py
  tests/ocpp_tests/test_sets/ocpp16/smart_charging_profiles/relative_profiles.py
  tests/ocpp_tests/test_sets/ocpp16/smart_charging_profiles/unplausable_profiles.py
  tests/ocpp_tests/test_sets/ocpp16/smart_charging_tests.py
  tests/ocpp_tests/test_sets/ocpp201/california_pricing.py
  tests/ocpp_tests/test_sets/ocpp201/display_message.py
  tests/ocpp_tests/test_sets/ocpp201/provisioning.py
  tests/ocpp_tests/test_sets/ocpp201/remote_control.py
  tests/ocpp_tests/test_sets/ocpp201/reservations.py
  tests/pytest.ini
Labels: include-in-release

#1146 Update libocpp to 0.26.0
  dependencies.yaml
Labels: include-in-release

#1138 Adapt to generated (in)equality operators for types in ev-cli v0.5.2
  cmake/ev-project-bootstrap.cmake
  dependencies.yaml
  modules/Auth/include/AuthHandler.hpp
  modules/EvseManager/Charger.hpp
Labels: include-in-release

#1115 EvseManager: Fix deadlock between hlc_mutex and state_machine_mutex
  modules/EvseManager/EvseManager.cpp
  modules/EvseManager/EvseManager.hpp
  modules/EvseManager/scoped_lock_timeout.hpp
Labels: bug, include-in-release

#1145 Auth: Fix interface
  interfaces/auth.yaml
  modules/Auth/main/authImpl.cpp
  modules/Auth/main/authImpl.hpp
Labels: include-in-release

#1126 GenericPowermeter: improve error handling
  modules/GenericPowermeter/CMakeLists.txt
  modules/GenericPowermeter/main/powermeterImpl.cpp
  modules/GenericPowermeter/main/powermeterImpl.hpp
Labels: include-in-release
